#!/bin/bash
################################################################################
# CODITECT EXPORT Command
#
# Simple wrapper for export-context.sh
# Usage: Just type "EXPORT" or "./commands/export [description]"
################################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXPORT_SCRIPT="$SCRIPT_DIR/../scripts/export-context.sh"

# Pass all arguments to the export script
"$EXPORT_SCRIPT" "$@"
